jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "hello world TJRM-3 and 4 and 5 and 5"
  deploy:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "hello world TJRM-3 and 4 and 5 and 5"
orbs:
  jira: circleci/jira@1.3.1
version: 2.1
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify
      - deploy:
          name: Dev East
          post-steps:
            - jira/notify:
                environment_type: development
                job_type: deployment
          requires:
            - build

